import {createContext} from 'react';
export type Locale='en'|'zh';
export const LocaleContext=createContext<Locale>('en');
export const zh:Record<string,string>={
 'Subject in front':'主体置于网格前','Detects people locally. Other subjects may not be detected.':'在本机检测人物，其他主体可能无法识别。','Detecting subject…':'正在检测主体…','Person detected':'已检测到人物','No person detected — grid unchanged':'未检测到人物，网格保持不变','Detection unavailable — grid unchanged':'检测暂不可用，网格保持不变',
 'PHOTO ADJUSTMENTS':'照片调整','Highlights':'高光','Shadows':'阴影','Black point':'黑场','Noise reduction':'降噪',
 'Portrait Study':'人像研究',
 'Black / White':'黑 / 白',
 'Custom colors':'自定义配色','Shape color':'形状颜色','Geometry background':'几何背景色','Label color':'标注颜色','Custom link color':'自定义连线颜色','Link color':'连线颜色','Orbit color':'轨道颜色','Engraving color':'雕刻线颜色','Halftone ink':'网点颜色','Halftone background':'半色调背景色','Dither ink':'抖色暗部','Dither background':'抖色亮部','Custom pixel colors':'自定义像素配色','Pixel shadows':'像素暗部','Pixel highlights':'像素亮部','Outline color':'边框颜色','Window halftone ink':'窗口网点颜色','Window halftone background':'窗口半色调背景色','Window dither ink':'窗口抖色暗部','Window dither background':'窗口抖色亮部','Window engraving color':'窗口雕刻线颜色','Window contour color':'窗口等高线颜色','Custom window pixel colors':'自定义窗口像素配色','Window pixel shadows':'窗口像素暗部','Window pixel highlights':'窗口像素亮部',

 'Window outline':'窗口边框','PORTRAIT WINDOW':'人像窗口','Portrait window':'人像窗口','Window style':'窗口风格','Original photo':'原始照片','Window width':'窗口宽度','Window height':'窗口高度','Window position X':'窗口水平位置','Window position Y':'窗口垂直位置','Window detail':'窗口纹理间距','Center window':'居中窗口','Move portrait window':'移动人像窗口','Drag the window to move it. Drag a corner to resize. Handles are not exported.':'拖动窗口移动，拖动角点调整大小。控制框不会导出。',

 'NO SOURCE':'未导入图片', 'Designed by':'设计者','Choose photo':'选择照片','STILL /':'照片 /','Editing mode':'编辑模式','Easy':'简易','Pro':'专业','Upload':'导入','Export':'导出','Exporting…':'正在导出…','SOURCE':'图像源','LOCAL':'本地','ON':'开','OFF':'关','Drop your image here':'将图片拖放到这里','or click to browse':'或点击选择文件','JPG · PNG · WEBP / MAX 32 MB':'JPG · PNG · WEBP / 最大 32 MB','Source thumbnail':'原图缩略图','Use sample photograph':'使用示例照片','COMPOSITION':'构图','Aspect ratio':'画面比例','Original':'原始比例','Square / 1:1':'方形 / 1:1','Portrait / 4:5':'竖幅 / 4:5','Story / 9:16':'全屏竖幅 / 9:16','Landscape / 16:9':'横幅 / 16:9','Position X':'水平位置','Position Y':'垂直位置','Reposition within a crop. Your original stays intact.':'调整裁切区域中的位置，原始图片不会改变。',
 'GEOMETRY FIELD':'几何场','Generative geometry':'生成几何图形','Distribution':'采样分布','Image edges':'图像边缘','Luminance':'亮度分布','Uniform scatter':'均匀散点','Node density':'节点密度','Edge threshold':'边缘阈值','Source visibility':'原图可见度','Seed':'随机种子','New seed':'更换种子','The same seed reproduces the same geometry at every export size.':'相同的种子可在任意导出尺寸下重现相同的几何图形。','SHAPE SYSTEM':'形状系统','Circle':'圆形','Square':'方形','Diamond':'菱形','Cross':'十字','Bracket':'角标','Triangle':'三角形','Mixed':'混合','Glyph':'字符','Minimum size':'最小尺寸','Maximum size':'最大尺寸','Edge alignment':'边缘方向对齐','Size hierarchy':'尺寸层级','Shape stroke':'形状线宽','Shape opacity':'形状不透明度','Filled shapes':'填充形状','Geometry color':'几何配色','Source colors':'原图颜色','White on charcoal':'深底白色','Black on paper':'浅底黑色','Cobalt on paper':'浅底钴蓝','CONNECTIONS':'连接系统','Link system':'连线方式','None':'无','Proximity':'邻近连接','Delaunay mesh':'德劳内三角网','Edge chain':'边缘链','Radial':'放射连接','Orthogonal':'直角连接','Hybrid':'混合连接','Link distance':'连接距离','Link width':'连线宽度','Link opacity':'连线不透明度',
 'TOPOGRAPHIC':'等高线','Contour lines':'等高线条','Contour color':'等高线颜色','Levels':'层级数量','Line width':'线条宽度','Opacity':'不透明度','GEOMETRIC MOSAIC':'几何马赛克','Triangle field':'三角拼贴','Cell size':'单元尺寸','Overlay opacity':'叠加不透明度','ON-DEVICE PROCESSING':'在本机处理','LOOK PRESET':'风格预设','Look preset':'风格预设','Custom':'自定义','Randomize effects':'随机组合效果','Randomize':'随机组合','Randomize field':'随机生成几何场','Field random':'随机几何','Undo':'撤销','Undo (⌘/Ctrl Z)':'撤销（⌘/Ctrl Z）','Redo':'重做','Redo (⌘/Ctrl Shift Z)':'重做（⌘/Ctrl Shift Z）','Compare':'对比原图','FORM / IMAGE STUDY — 001':'FORM / 图像研究 — 001','Y / LUMINANCE':'Y / 亮度','Edited artwork preview':'作品预览','X / FRAME INDEX':'X / 画面序号','DRAG TO PAN':'拖动平移','IMAGE LOCKED':'图像已锁定','Lock image':'锁定图像','Unlock image':'解锁图像','Lock':'锁定','Unlock':'解锁','Zoom level':'缩放比例','Zoom out':'缩小','Zoom in':'放大','Fit':'适应画布','LOCAL ONLY':'仅在本机','NO UPLOADS':'无需上传','ORIGINAL SOURCE':'原始图像','PROCESSED IMAGE':'处理后的图像','Artwork ready':'作品已就绪','Rendering artwork…':'正在渲染作品…','Reading image…':'正在读取图片…','Loading sample…':'正在加载示例…','Upload a photograph to begin':'导入照片以开始创作',
 'FLOW ENGRAVING':'流线雕刻','Engraved lines':'雕刻线条','Engraving spacing':'雕刻间距','Flow strength':'起伏强度','Engraving width':'雕刻线宽','Engraving opacity':'雕刻不透明度','HALFTONE PRINT':'半色调印刷','Halftone dots':'半色调网点','Dot spacing':'网点间距','Dot scale':'网点大小','Screen angle':'网屏角度','DITHER + PIXEL':'抖色与像素','Ordered dithering':'有序抖色','Two-color palette':'双色调色板','Cobalt / Paper':'钴蓝 / 纸白','Ink / Cream':'墨黑 / 米白','Forest / Sage':'森林 / 鼠尾草','Rust / Sand':'铁锈 / 沙色','Dither size':'抖色尺寸','Pixelation':'像素化','Pixel size':'像素尺寸','GRID OVERLAY':'网格叠加','Artwork grid':'作品网格','Grid spacing':'网格间距','Grid thickness':'网格线宽','Grid color':'网格颜色','Grid opacity':'网格不透明度','COLOR + TONE':'色彩与影调','Brightness':'亮度','Contrast':'对比度','Saturation':'饱和度','Grayscale':'灰度','OUTPUT':'导出设置','Format':'格式','Export format':'导出格式','Scale':'倍数','Export scale':'导出倍数','OUTPUT SIZE':'输出尺寸','Export image':'导出图片','Rendering export…':'正在生成导出文件…','Full-resolution artwork. No watermark.':'完整分辨率作品，无水印。','Original resolution at 1×. Upscaling adds pixels, not detail.':'1× 保留原始分辨率。放大增加像素，不增加细节。','Original resolution':'原始分辨率','2× upscale':'2× 放大','Rendering order':'渲染顺序','Composition → Color → Pixel → Dither → Halftone → Contours → Grid → Engraving → Geometry → Circle chain → Portrait window':'构图 → 色彩 → 像素 → 抖色 → 半色调 → 等高线 → 网格 → 雕刻 → 几何 → 圆链 → 人像窗口','Reset adjustments':'重置调整','Editor panels':'编辑面板','Source':'原图','Preview':'预览','Effects':'效果','Drop to open your photograph':'拖放以打开照片','JPEG · PNG · WebP / stays on this device':'JPEG · PNG · WebP / 图片仅保留在本机','Dismiss error':'关闭错误提示',
 'Rotate your phone to portrait':'请将手机转为竖屏','Your edits will be here when you turn back.':'转回竖屏后，即可继续编辑。',
 'Node annotations':'节点标注','Maximum labels':'最多标注数','Label size':'标注字号','Sparse labels on prominent nodes: IDs, luminance L, and tangent angle θ. New seed changes the selection.':'仅标注部分显著节点：编号、亮度 L、切线角度 θ。更换种子可重新选择。','GEOMETRY CHAIN':'几何圆链','Circle chain':'圆链','Chain intersections':'圆交点','Chain count':'圆数量','Chain angle':'圆链角度','Base radius':'初始半径','Size ratio':'半径比例','Chain opacity':'圆链不透明度','Starts at a strong image edge and grows toward open space. Marks show true circle intersections.':'从显著边缘向开阔区域延伸，标记显示圆的真实交点。',
 'Orbital Study':'轨道研究','ORBITAL STUDY':'轨道研究','Orbit sequence':'轨道序列','Design':'设计',
 'Contour Atlas':'等高线图集','Geometric Portrait':'几何拼像','Cobalt Dither':'钴蓝抖色','Halftone Print':'半色调印刷','Pixel Memory':'像素记忆','Technical Grid':'技术网格','Edge Architecture':'边缘建筑','Ghost Constellation':'幽灵星座','Delaunay Mesh':'德劳内网格','Radial Specimen':'放射标本','Ortho Blueprint':'直角蓝图','Mixed Geometry':'混合几何','Flow Engraving':'流线雕刻','Glyph Study':'字符研究',
 'Choose a JPEG, PNG, or WebP image.':'请选择 JPEG、PNG 或 WebP 图片。','This file is too large. Choose an image under 32 MB.':'文件过大，请选择小于 32 MB 的图片。','This image is empty. Please choose another file.':'图片文件为空，请选择其他文件。','Choose an image under 50 megapixels and 10,000 pixels per side.':'请选择少于 5000 万像素、单边不超过 10000 像素的图片。','The sample could not load. Upload a photo to begin.':'示例加载失败，请导入照片以开始创作。','The source image could not be decoded.':'无法解码该图片。','Please load an image first.':'请先导入图片。','Please load an image.':'请导入图片。','Could not create the export.':'无法生成导出文件。','The image renderer stopped. Reload the page to continue.':'图像渲染器已停止，请刷新页面后重试。','Rendering failed. Try a smaller image.':'渲染失败，请尝试较小的图片。'
};
export function translate(locale:Locale,key:string):string{if(locale==='en')return key;if(zh[key])return zh[key];if(key.startsWith('Could not open image. '))return '无法打开图片。'+translate(locale,key.slice(22));if(key.startsWith('Export failed. '))return '导出失败。'+translate(locale,key.slice(15));if(key.startsWith('Exported '))return key.replace('Exported ','已导出 ');return key;}
